name: Test

on: [push]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Installing Packages
        run: yarn install
      - name: Starting Test
        run: yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Installing Packages
        run: yarn install
      - name: Starting Build
        run: yarn build
